[package]
name = "desktop"
version = "0.1.0"
authors = ["cannotilever <cannotilever@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {features = ["blocking"], version = "0.10"}